package com.lazybean.yaypipe.gamehelper;

public enum StatisticsType {
    TOTAL_PLAYTIME,
    TOTAL_UNDO,
    TOTAL_RESTART,
    TOTAL_TRY,
    TOTAL_FAIL,
    TOTAL_PIPE,

    BEST_TIME_EASY,
    BEST_TIME_NORMAL,
    BEST_TIME_HARD,
    BEST_TIME_EXTREME,
    BEST_TIME_MASTER,

    CLEAR_EASY,
    CLEAR_NORMAL,
    CLEAR_HARD,
    CLEAR_EXTREME,
    CLEAR_MASTER,

    HIGHSCORE_ALL,
    HIGHSCORE_EASY,
    HIGHSCORE_NORMAL,
    HIGHSCORE_HARD,
    HIGHSCORE_EXTREME,
    HIGHSCORE_MASTER,

    MOST_PIPE_CONNECTED,
    MOST_PIPE_CHANGED,
    MOST_UNDO,

    PIPE_TOP_BOTTOM_USE,
    PIPE_LEFT_RIGHT_USE,
    PIPE_LEFT_TOP_USE,
    PIPE_LEFT_BOTTOM_USE,
    PIPE_RIGHT_TOP_USE,
    PIPE_RIGHT_BOTTOM_USE,
    PIPE_ALL_DIRECTION_USE,
    PIPE_ALL_DIRECTION_FULL_USE;


}
